# Generated by Django 4.2.23 on 2025-07-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthlycoffee', '0004_alter_coffeeroaster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeroaster',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='monthlycoffee.coffeeroaster')),
            ],
        ),
    ]
