# Generated by Django 4.2.23 on 2025-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlycoffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeroaster',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
