# Generated by Django 4.2.23 on 2025-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlycoffee', '0002_coffeeroaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeroaster',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
