# Generated by Django 4.2.23 on 2025-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthlycoffee', '0005_remove_coffeeroaster_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeroaster',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/roasters_assets'),
        ),
    ]
